version: "3.9"

services:

   dev-enviroment:
      build: 
        context: .
        dockerfile: dev.Dockerfile
      ports:
        - 8895:8895
      runtime: nvidia
      volumes:
        - .:/app/.
      env_file:
        ./.env.local